before_script:
    - python --version
    - yum install -y python-devel python-pip
    - pip install setuptools
    - python setup.py develop
    - sff --help

test:
    script:
        - sff tests schema