language: python
sudo: true

before_install:
  - python --version
  - sudo apt-get update
  - sudo apt-get install build-essential
#  - sudo apt-get install -y python-dev python-pip
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coveralls
  - pip install h5py

install:
  - python setup.py develop
  - sff --help

script:
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests schema -v 3
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests readers -v 3
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests formats -v 3
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests notes -v 3
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests core -v 3
  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/*" `which sff` tests main -v 3

after_success:
  - coveralls
