language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: true

before_install:
  - python --version
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coverage
  - pip install coveralls
  - pip install numpy
#  - pip install "numpy<=1.15.4"
  - pip install pytest
  - pip install pytest-cov

install:
  - python setup.py develop
#  - sff --help

script:
  - pytest --cov=./sfftk sfftk/unittests
#  - coverage run --include="/home/travis/build/emdb-empiar/sfftk/sfftk/*" --omit="/home/travis/build/emdb-empiar/sfftk/sfftk/test_data","/home/travis/build/emdb-empiar/sfftk/sfftk/unittests" `which sff` tests all -v 3

after_success:
  - coveralls
