language: python
sudo: true

before_install:
  - python --version
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install -y python-dev python-pip
  - pip -V
  - pip install setuptools
  - pip install coveralls

install:
  - python setup.py develop
  - sff --help

script:
  - sff tests schema -v 3
  - sff tests readers -v 3
  - sff tests formats -v 3
  - sff tests notes -v 3
  - sff tests core -v 3
  - sff tests main -v 3

after_script:
  - coveralls
